import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Users,
  Briefcase,
  CreditCard,
  DollarSign,
  Map,
  Network,
  Megaphone,
  MessageCircle,
  Shield,
  Bell,
  Settings2,
  BarChart3,
  FileText,
  FileWarning,
  BookOpenCheck,
  Code2,
} from 'lucide-react';

export interface AdminMenuItem {
  label: string;
  icon?: LucideIcon;
  route?: string;
  children?: AdminMenuItem[];
}

export const adminMenu: AdminMenuItem[] = [
  {
    label: 'Dashboard',
    icon: LayoutDashboard,
    route: '/admin/dashboard',
  },
  {
    label: 'Utilisateurs',
    icon: Users,
    children: [
      { label: 'Vue globale', route: '/admin/users' },
      { label: 'Clients', route: '/admin/users/clients' },
      { label: 'Prestataires', route: '/admin/users/providers' },
      { label: 'Employés', route: '/admin/users/employees' },
      { label: 'Rôles & permissions', route: '/admin/users/roles' },
    ],
  },
  {
    label: 'Réservations',
    icon: Briefcase,
    children: [
      { label: 'Vue globale', route: '/admin/bookings' },
      { label: 'Réservations à venir', route: '/admin/bookings/upcoming' },
      { label: 'Historique & terminées', route: '/admin/bookings/history' },
      { label: 'Annulées & échouées', route: '/admin/bookings/cancelled' },
    ],
  },
  {
    label: 'Finances & Paiements',
    icon: CreditCard,
    children: [
      { label: 'Vue générale', route: '/admin/finance' },
      { label: 'Paiements clients', route: '/admin/finance/client-payments' },
      { label: 'Versements prestataires', route: '/admin/finance/provider-payouts' },
      { label: 'Remboursements', route: '/admin/finance/refunds' },
      { label: 'Factures', route: '/admin/finance/invoices' },
      { label: 'Commissions & taxes', route: '/admin/finance/commissions' },
      { label: 'Mollie & webhooks', route: '/admin/finance/mollie' },
      { label: 'Exports', route: '/admin/finance/exports' },
      { label: 'Règles & alertes', route: '/admin/finance/alerts' },
    ],
  },
  {
    label: 'Services & Tarifs',
    icon: DollarSign,
    children: [
      { label: 'Catalogue', route: '/admin/services' },
      { label: 'Options & add-ons', route: '/admin/services/categories' },
      { label: 'Grille tarifaire', route: '/admin/services/pricing' },
      { label: 'Surcharges & extras', route: '/admin/services/packs' },
      { label: 'Aperçu client', route: '/admin/services/restrictions' },
      { label: 'Habilitations prestataires', route: '/admin/services/habilitations' },
      { label: 'Historique & logs', route: '/admin/services/logs' },
    ],
  },
  {
    label: 'Zones & Matching',
    icon: Map,
    children: [
      { label: 'Catalogue des zones', route: '/admin/zones' },
      { label: 'Couverture prestataires', route: '/admin/zones/coverage' },
      { label: 'Paramètres matching', route: '/admin/zones/matching' },
      { label: 'Zones en tension', route: '/admin/zones/tensions' },
      { label: 'Diagnostic matching', route: '/admin/zones/diagnostic' },
    ],
  },
  {
    label: 'Smart Matching',
    icon: Network,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/matching' },
      { label: 'Règles de scoring', route: '/admin/matching/scoring' },
      { label: 'Scénarios', route: '/admin/matching/scenarios' },
      { label: 'Journal / Logs', route: '/admin/matching/logs' },
      { label: 'Sandbox & simulation', route: '/admin/matching/simulation' },
      { label: 'Politiques business', route: '/admin/matching/policies' },
      { label: 'Garde-fous', route: '/admin/matching/guardrails' },
    ],
  },
  {
    label: 'Marketing & Codes promo',
    icon: Megaphone,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/marketing' },
      { label: 'Codes promo', route: '/admin/marketing/promo' },
      { label: 'Campagnes', route: '/admin/marketing/campaigns' },
      { label: 'Parrainage & crédits', route: '/admin/marketing/referrals' },
      { label: 'Landing & SEO', route: '/admin/marketing/landing' },
      { label: 'Analytics marketing', route: '/admin/marketing/analytics' },
      { label: 'Paramètres', route: '/admin/marketing/settings' },
    ],
  },
  {
    label: 'Feedback & Qualité',
    icon: MessageCircle,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/feedback' },
      { label: 'Avis & évaluations', route: '/admin/feedback/reviews' },
      { label: 'Scores prestataires', route: '/admin/feedback/providers' },
      { label: 'Incidents & litiges', route: '/admin/feedback/incidents' },
      { label: 'NPS & satisfaction', route: '/admin/feedback/nps' },
      { label: 'Programmes qualité', route: '/admin/feedback/programs' },
      { label: 'Alertes automatiques', route: '/admin/feedback/alerts' },
    ],
  },
  {
    label: 'Support & Litiges',
    icon: Shield,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/support' },
      { label: 'Tickets', route: '/admin/support/tickets' },
      { label: 'Litiges financiers', route: '/admin/support/disputes' },
      { label: 'Communications', route: '/admin/support/communications' },
      { label: 'SLA & KPI', route: '/admin/support/sla' },
      { label: 'Automatisations', route: '/admin/support/automations' },
      { label: 'Médiation', route: '/admin/support/mediation' },
    ],
  },
  {
    label: 'Notifications & Automatisation',
    icon: Bell,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/automation' },
      { label: 'Centre de notification', route: '/admin/automation/center' },
      { label: 'Templates', route: '/admin/automation/templates' },
      { label: 'Workflows', route: '/admin/automation/workflows' },
      { label: 'Webhooks', route: '/admin/automation/webhooks' },
      { label: 'Analytics', route: '/admin/automation/analytics' },
      { label: 'Consentements', route: '/admin/automation/consents' },
      { label: 'Planification', route: '/admin/automation/scheduling' },
    ],
  },
  {
    label: 'Système & Intégrations',
    icon: Settings2,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/system' },
      { label: 'Intégrations externes', route: '/admin/system/integrations' },
      { label: 'Environnements', route: '/admin/system/environments' },
      { label: 'Logs système', route: '/admin/system/logs' },
      { label: 'Clés API', route: '/admin/system/api-keys' },
      { label: 'Statut serveurs', route: '/admin/system/status' },
      { label: 'Sécurité', route: '/admin/system/security' },
      { label: 'Import / Export', route: '/admin/system/import-export' },
    ],
  },
  {
    label: 'Analytics & BI',
    icon: BarChart3,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/analytics' },
      { label: 'Matching', route: '/admin/analytics/matching' },
      { label: 'Géographie', route: '/admin/analytics/geography' },
      { label: 'Finances', route: '/admin/analytics/finance' },
      { label: 'Prestataires', route: '/admin/analytics/providers' },
      { label: 'Clients', route: '/admin/analytics/clients' },
      { label: 'BI & exports', route: '/admin/analytics/bi' },
      { label: 'Insights automatiques', route: '/admin/analytics/insights' },
    ],
  },
  {
    label: 'Documents & Identité',
    icon: FileText,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/documents' },
      { label: 'Prestataires', route: '/admin/documents/providers' },
      { label: 'Entreprises', route: '/admin/documents/companies' },
      { label: 'Workflow', route: '/admin/documents/workflow' },
      { label: 'Intégrations', route: '/admin/documents/integrations' },
      { label: 'Rappels & automatisations', route: '/admin/documents/reminders' },
    ],
  },
  {
    label: 'Conformité & RGPD',
    icon: FileWarning,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/compliance' },
      { label: 'Consentements', route: '/admin/compliance/consents' },
      { label: 'Sécurité', route: '/admin/compliance/security' },
      { label: 'Demandes RGPD', route: '/admin/compliance/requests' },
      { label: 'Politiques & CGU', route: '/admin/compliance/policies' },
      { label: 'Paiements & PSD2', route: '/admin/compliance/payments' },
      { label: 'Automatisation', route: '/admin/compliance/automation' },
    ],
  },
  {
    label: 'CMS & Pages',
    icon: BookOpenCheck,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/cms' },
      { label: 'Pages statiques', route: '/admin/cms/pages' },
      { label: 'Blog & articles', route: '/admin/cms/blog' },
      { label: 'Landing pages', route: '/admin/cms/landing' },
      { label: 'Templates email', route: '/admin/cms/email' },
    ],
  },
  {
    label: 'Module Développeurs',
    icon: Code2,
    children: [
      { label: 'Vue d’ensemble', route: '/admin/dev-tools' },
      { label: 'Webhooks', route: '/admin/dev-tools/webhooks' },
      { label: 'Logs', route: '/admin/dev-tools/logs' },
      { label: 'Jobs & queues', route: '/admin/dev-tools/jobs' },
      { label: 'Intégrations', route: '/admin/dev-tools/integrations' },
      { label: 'Sandbox', route: '/admin/dev-tools/sandbox' },
      { label: 'Versions & backups', route: '/admin/dev-tools/version' },
      { label: 'Feature flags', route: '/admin/dev-tools/flags' },
    ],
  },
];
